// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
)

type Livro struct {
	ID        int64
	Nome      string
	Descricao sql.NullString
	Src       sql.NullString
}
