// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: queries.sql

package db

import (
	"context"
)

const getLivros = `-- name: GetLivros :many
SELECT id, nome, descricao, src FROM livros
`

func (q *Queries) GetLivros(ctx context.Context) ([]Livro, error) {
	rows, err := q.db.QueryContext(ctx, getLivros)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Livro
	for rows.Next() {
		var i Livro
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.Src,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
